spring:
  datasource:
    url: jdbc:mysql://localhost:3306/real_estate_am?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root2000

  jpa:
    hibernate:
      ddl-auto: update
#  Mail config
  mail:
    host: smtp.gmail.com
    port: 587
    username: martirosyansamvel109@gmail.com
    password: dmwfrjodlwjnkyej
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  error:
    whitelabel:
      enabled: false

file:
  upload:
    dir: D:\\upload